### PR TITLE
feat(init): launch from .cs file first

### PR DESCRIPTION
**Pull request by tris203**
Allow users to open a .cs file first

### CODE REVIEW

**Comment by tris203** [comment]
Currently blocked by https://github.com/seblj/roslyn.nvim/pull/100

**Review by neubaner — APPROVED** [review]
Works for me :)

**Comment by kmoschcau** [comment]
Hi, just from looking at the code, you are missing `.cshtml` files with this solution.

**Comment by tris203** [comment]
> Hi, just from looking at the code, you are missing `.cshtml` files with this solution.

Please create an issue or a PR :)

**Pull request merged**
